# Generated by Django 6.0.1 on 2026-01-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('rate', models.FloatField(default=10.0)),
                ('role', models.CharField(blank=True, choices=[('CUSTOMER', 'Customer'), ('LANDLORD', 'Landlord')], max_length=10, null=True)),
            ],
        ),
    ]
