# Generated by Django 4.2.5 on 2026-01-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rates_count',
            field=models.IntegerField(default=0),
        ),
    ]
