# Generated by Django 4.2.5 on 2026-01-18 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_rates_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rates_count',
        ),
    ]
