# Generated by Django 4.2.5 on 2026-01-27 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='reservations',
        ),
        migrations.AddField(
            model_name='reservation',
            name='accommodation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.accommodation'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
